-- Catàleg dels expositors: només es venen articles disponibles al servei avui.
return {
 ['Esmorzars']={items={'coca','mel_bosc','ametlles'},text='Cereals, mel i fruits secs per començar el dia.'},
 ['Pasta i arròs']={items={'arros','pasta'},text='Paquets de pasta i sacs petits d’arròs.'},
 ['Conserves']={items={'conserva'},text='Pots i llaunes ordenats per producte.'},
 ['Làctics']={items={'llet','formatge'},text='Neveres amb llet, iogurts i formatges.'},
 ['Begudes']={items={'aigua','suc_raim'},text='Aigua i sucs. Els envasos buits van al contenidor corresponent.'},
 ['Neteja']={text='Sabó, detergents i estris de neteja. No són aliments!'},
 ['Dolços']={items={'coca','mel_bosc'},text='Galetes, coques i petits capricis.'},
 ['Higiene']={items={'botiqui','farmaciola'},text='Higiene personal i primers auxilis.'},
 ['Cuina del món']={items={'sopa_peix','arros'},text='Ingredients i plats de diferents cuines.'},
 ['Mascotes']={text='Menjar, bols i joguines per als animals de casa.'},
 ['Forn']={items={'pa','coca'},text='El pa acabat de fer encara fa bona olor.'},
 ['Fruita i verdura']={items={'poma','mandarina','tomaquet'},text='Fruita de temporada i caixes de verdura.'},
 ['Congelats']={items={'peix'},text='Productes congelats. Cal mantenir la cadena del fred.'},
 ['Peixateria']={items={'peix','sopa_peix'},text='Peix sobre gel i plats preparats de la peixateria.'},
 ['Fusta']={text='Taulons, llistons i mostres de fusta de diferents acabats.'},
 ['Pintura']={text='Pots de pintura i una carta de colors. Pots comparar els acabats aquí.'},
 ['Eines']={items={'destral_bosc','martell_pedrera','casc_miner'},text='Eines i protecció: tria el material adequat per al treball.'},
 ['Rajoles']={text='Mostres de rajola: terracota, pedra i ceràmica.'},
 ['Lampisteria']={text='Tubs, colzes, aixetes i juntes de diferents mides.'},
 ['Jardí']={items={'armilla_explorador','mapa_muntanya'},text='Plantes, testos, substrat i accessoris per treballar a fora.'},
 ['Magatzem']={text='Palets amb material. Demana ajuda al personal per a les peces pesades.'},
 ['Il·luminació']={items={'llanterna'},text='Llums de mostra encesos i llanternes per a les aventures.'},
 ['Informació']={text='Eines i pintura als passadissos centrals; jardí a l’esquerra; il·luminació a la dreta. Les caixes són al costat de la sortida.'},
 ['Carros']={text='Aquí s’aparquen els carros. Els clients recorren els passadissos amb la compra.'},
 ['Cistelles']={text='Cistelles per a una compra petita. Les caixes són al costat de la sortida.'},
}
